# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\entryform.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EntryForm(object):
    def setupUi(self, EntryForm):
        EntryForm.setObjectName("EntryForm")
        EntryForm.resize(600, 300)
        EntryForm.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.verticalLayout = QtWidgets.QVBoxLayout(EntryForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(EntryForm)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.toolBox = QtWidgets.QToolBox(EntryForm)
        self.toolBox.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.toolBox.setObjectName("toolBox")
        self.Gewicht = QtWidgets.QWidget()
        self.Gewicht.setGeometry(QtCore.QRect(0, 0, 582, 91))
        self.Gewicht.setObjectName("Gewicht")
        self.formLayout = QtWidgets.QFormLayout(self.Gewicht)
        self.formLayout.setObjectName("formLayout")
        self.gewicht = QtWidgets.QDoubleSpinBox(self.Gewicht)
        self.gewicht.setDecimals(1)
        self.gewicht.setSingleStep(0.1)
        self.gewicht.setObjectName("gewicht")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gewicht)
        self.label_2 = QtWidgets.QLabel(self.Gewicht)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.Gewicht)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.datumGewicht = QtWidgets.QDateEdit(self.Gewicht)
        self.datumGewicht.setDate(QtCore.QDate(2000, 1, 4))
        self.datumGewicht.setObjectName("datumGewicht")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.datumGewicht)
        self.toolBox.addItem(self.Gewicht, "")
        self.Umfaenge = QtWidgets.QWidget()
        self.Umfaenge.setGeometry(QtCore.QRect(0, 0, 582, 91))
        self.Umfaenge.setObjectName("Umfaenge")
        self.widget = QtWidgets.QWidget(self.Umfaenge)
        self.widget.setGeometry(QtCore.QRect(10, 0, 511, 111))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.oberschenkel = QtWidgets.QDoubleSpinBox(self.frame)
        self.oberschenkel.setDecimals(1)
        self.oberschenkel.setSingleStep(0.1)
        self.oberschenkel.setObjectName("oberschenkel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.oberschenkel)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.bauch = QtWidgets.QDoubleSpinBox(self.frame)
        self.bauch.setDecimals(1)
        self.bauch.setSingleStep(0.1)
        self.bauch.setObjectName("bauch")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bauch)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.huefte = QtWidgets.QDoubleSpinBox(self.frame)
        self.huefte.setDecimals(1)
        self.huefte.setObjectName("huefte")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.huefte)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.brust = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.brust.setDecimals(1)
        self.brust.setSingleStep(0.1)
        self.brust.setObjectName("brust")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.brust)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.bizeps = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.bizeps.setDecimals(1)
        self.bizeps.setSingleStep(0.1)
        self.bizeps.setObjectName("bizeps")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bizeps)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.datumUmfaenge = QtWidgets.QDateEdit(self.frame_2)
        self.datumUmfaenge.setObjectName("datumUmfaenge")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.datumUmfaenge)
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.toolBox.addItem(self.Umfaenge, "")
        self.Ernaehrung = QtWidgets.QWidget()
        self.Ernaehrung.setGeometry(QtCore.QRect(0, 0, 582, 91))
        self.Ernaehrung.setObjectName("Ernaehrung")
        self.frame_3 = QtWidgets.QFrame(self.Ernaehrung)
        self.frame_3.setGeometry(QtCore.QRect(300, 0, 271, 66))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.protein = QtWidgets.QSpinBox(self.frame_3)
        self.protein.setMaximum(999)
        self.protein.setObjectName("protein")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.protein)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.fett = QtWidgets.QSpinBox(self.frame_3)
        self.fett.setMaximum(999)
        self.fett.setObjectName("fett")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fett)
        self.frame_4 = QtWidgets.QFrame(self.Ernaehrung)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 291, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.gesamtKcal = QtWidgets.QSpinBox(self.frame_4)
        self.gesamtKcal.setMaximum(9999)
        self.gesamtKcal.setObjectName("gesamtKcal")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gesamtKcal)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.kohlenhydrate = QtWidgets.QSpinBox(self.frame_4)
        self.kohlenhydrate.setMaximum(999)
        self.kohlenhydrate.setObjectName("kohlenhydrate")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kohlenhydrate)
        self.datumErnaehrung = QtWidgets.QDateEdit(self.frame_4)
        self.datumErnaehrung.setObjectName("datumErnaehrung")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.datumErnaehrung)
        self.toolBox.addItem(self.Ernaehrung, "")
        self.Koerperfettanteil = QtWidgets.QWidget()
        self.Koerperfettanteil.setGeometry(QtCore.QRect(0, 0, 582, 91))
        self.Koerperfettanteil.setObjectName("Koerperfettanteil")
        self.frame_5 = QtWidgets.QFrame(self.Koerperfettanteil)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 581, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.frame_5)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.kfa = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.kfa.setDecimals(1)
        self.kfa.setSingleStep(0.1)
        self.kfa.setObjectName("kfa")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kfa)
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.datumKFA = QtWidgets.QDateEdit(self.frame_5)
        self.datumKFA.setObjectName("datumKFA")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.datumKFA)
        self.toolBox.addItem(self.Koerperfettanteil, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.lustigLol = QtWidgets.QLabel(EntryForm)
        self.lustigLol.setTextFormat(QtCore.Qt.RichText)
        self.lustigLol.setObjectName("lustigLol")
        self.verticalLayout.addWidget(self.lustigLol)
        self.buttonBox = QtWidgets.QDialogButtonBox(EntryForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EntryForm)
        self.toolBox.setCurrentIndex(2)
        self.toolBox.layout().setSpacing(6)
        self.buttonBox.rejected.connect(EntryForm.reject)
        QtCore.QMetaObject.connectSlotsByName(EntryForm)

    def retranslateUi(self, EntryForm):
        _translate = QtCore.QCoreApplication.translate
        EntryForm.setWindowTitle(_translate("EntryForm", "Gewicht eintragen"))
        self.label.setText(_translate("EntryForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Neuer Eintrag:</span></p></body></html>"))
        self.label_2.setText(_translate("EntryForm", "Gewicht:"))
        self.label_3.setText(_translate("EntryForm", "Datum: "))
        self.datumGewicht.setDisplayFormat(_translate("EntryForm", "dd.MM.yyyy"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Gewicht), _translate("EntryForm", "Gewicht"))
        self.label_4.setText(_translate("EntryForm", "Oberschenkel:"))
        self.label_5.setText(_translate("EntryForm", "Bauch:"))
        self.label_6.setText(_translate("EntryForm", "Hüfte:"))
        self.label_7.setText(_translate("EntryForm", "Brust:"))
        self.label_13.setText(_translate("EntryForm", "Bizeps:"))
        self.label_16.setText(_translate("EntryForm", "Datum:"))
        self.datumUmfaenge.setDisplayFormat(_translate("EntryForm", "dd.MM.yyyy"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Umfaenge), _translate("EntryForm", "Umfänge"))
        self.label_10.setText(_translate("EntryForm", "Protein:"))
        self.label_11.setText(_translate("EntryForm", "Fett:"))
        self.label_8.setText(_translate("EntryForm", "Gesamtkcal:"))
        self.label_15.setText(_translate("EntryForm", "Datum:"))
        self.label_9.setText(_translate("EntryForm", "Kohlenhydrate:"))
        self.datumErnaehrung.setDisplayFormat(_translate("EntryForm", "dd.MM.yyyy"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Ernaehrung), _translate("EntryForm", "Ernährung"))
        self.label_12.setText(_translate("EntryForm", "KFA:"))
        self.label_14.setText(_translate("EntryForm", "Datum:"))
        self.datumKFA.setDisplayFormat(_translate("EntryForm", "dd.MM.yyyy"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Koerperfettanteil), _translate("EntryForm", "Körperfettanteil"))
        self.lustigLol.setText(_translate("EntryForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Escht wird äbs eigetrooche!</span></p></body></html>"))
